### ISSUE TITLE
Package Status

### ISSUE THREAD

**Issue by Nosferican** [shashi/WebDriver.jl#3]
It seems the package hasn't been updated recently (last commits date three years ago). Is the project active with plans to bring web driver functionality to `julia 1`?

If so, there have been a few improvements in web driver interfaces such as the latest release of [RSelenium](https://github.com/ropensci/RSelenium) that would be nice to have (e.g., using Docker containers).

**Comment by Nosferican** [comment]
Bump.

**Comment by shashi** [comment]
I have no plans to continue working on this project. So it's up for adaption if you want to work on it :)

Most of the code is auto-generated by the script in `scripts/` using the WebDriver docs.

**Comment by Nosferican** [comment]
I was able to implement the WebDriver API using HTTP.jl and JSON3.jl. It allows for connecting to any listening server (e.g., a Docker selenium/standalone-chrome container). That’s the approach used for example in RSelenium. I am taking some time off in December so hopefully then I can finish testing it and register it. Once I push the repo, I would love if you could take a look at it in case there are any suggestions.

**Comment by Nosferican** [comment]
Project to revive the functionality is now at https://github.com/Nosferican/WebDriver.jl. Feel free to check it out and let me know any feedback.

**Comment by Nosferican** [comment]
I have registered it through https://github.com/JuliaRegistries/General/pull/11481. Cheers!
